site_name: Roblox CAuth
repo_name: Roblox CAuth Project
repo_url: https://LegitCirtuitz.github.io/rblxcauth/
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
nav:
  - Home: index.md
